name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Sets up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Lint the code
      - name: Run ESLint
        run: npm run lint

      # Run tests
      # Note: Add test scripts in package.json if available
      # - name: Run tests
      #   run: npm test

      # Build the project
      - name: Build the project
        run: npm run build

      # Deploy to GitHub Pages (Optional)
      # - name: Deploy to GitHub Pages
      #   if: success()
      #   run: |
      #     npm install -g gh-pages
      #     npm run build
      #     gh-pages -d dist -r https://<GITHUB_TOKEN>@github.com/<YOUR_USERNAME>/<YOUR_REPOSITORY>.git
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
